title:
description:
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
repo_url: "https://github.com/zelang-dev/athena"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist